# Generated by Django 4.0 on 2023-10-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(default='Share your experience with us...', max_length=500),
        ),
    ]
